### ISSUE TITLE
BUG FIX: Needtrans/Duflu merger needs reversion

### ISSUE THREAD

**Issue by HalHaynes** [wikimedia-gadgets/twinkle#1365]
In November 2020, @Amorymeltzer merged the "needs translation" and "needs translation cleanup" templates **needtrans** and **duflu**. I don't know what the impetus for it was, but the result is that the message being posted to the ["Pages needing translation into English"](https://en.wikipedia.org/wiki/Wikipedia:Pages_needing_translation_into_English) project page for articles written in other languages now reads the same as the message that's posted for articles in English that has been poorly translated from another language: "The initial language of this article was [language]." For articles that *need* translation, the message should be "The language of the article is [language]." The other message doesn't make sense in this context.

The commit in question is 555351cfa834c3ac7d8cced5183000ba16a92058.

**Comment by siddharthvp** [comment]
@HalHaynes can you link a diff for the problematic edit(s)?

**Comment by HalHaynes** [comment]
Hi, @siddharthvp . See the commit I'd provided, 555351cfa834c3ac7d8cced5183000ba16a92058, which consists of just a few deletions and additions, all within one file. Reverting it would have to be combined with reverting the Needtrans and Duflu templates. All of this was the outcome of a template discussion [here](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_October_31#Template:Duflu), a very short one to which I contributed a peripheral comment but where I didn't pay attention to the foreseeable outcome, which is that an incorrect message is being displayed for articles needing translation.

**Comment by siddharthvp** [comment]
Looking at the [template code](https://en.wikipedia.org/w/index.php?title=Template:Needtrans&action=edit) it does appear to support the intended wording, which suggests a code change here may be what's needed.

**Comment by HalHaynes** [comment]
That template provides two options:

1.  If `orig` is provided, it produces, for example, "The original Portuguese article is [pt:Hello](https://pt.wikipedia.org/wiki/Hello)."
1. Otherwise, it produces, for example, "The initial language was Portuguese."

The latter is what appears now for *all* entries, though it's suited only for requests for clean-up to rough translations. The former would also apply only to clean-up to rough translations; by default, it's assumed that, given the initial language, the source article can be found among the article's interlanguage links but, if there is no link there, this is the way to display it in the  message.

I don't see any way in which this template, in its current state, would display the message "The language of the article is Portuguese", which is what is called for in the case of articles needing translation. Further, even if that option were provided, the code here no longer appears to make such a distinction when generating the tag. It generates the same tag in all cases.

**Comment by HalHaynes** [comment]
Test these anywhere:

`{{subst:needtrans|pg=Hello|Language=Portuguese|orig=pt:Óla}}`

`{{subst:needtrans|pg=Hello|Language=Portuguese}}`

**Comment by siddharthvp** [comment]
@HalHaynes Okay, so can you fix the template (or get it fixed by someone)?

**Comment by siddharthvp** [comment]
Started a section on the talk page: https://en.wikipedia.org/wiki/Template_talk:Needtrans#Incomplete_merger_from_Template:Duflu

**Comment by HalHaynes** [comment]
It's been almost two years, but this problem came back to mind and I came back to look where we'd left things. The difference is that since then I've learned to find my way around a GitHub repository. I see exactly what needs to change:

1. In modules/friendlytag.js, currently at[ line 1385](https://github.com/wikimedia-gadgets/twinkle/blob/0654f8c1beefaefd807e6a045fdd3315c854afdb/modules/friendlytag.js#L1385), a variable called `templateText` is assigned, including the reference to the `needtrans` template. It is then used in both branches of the next if-else block. Its value should, instead, be set separately in the two branches, to use `duflu` in the "rough translation" branch and to use `needtrans` in the other one.
2. Back in Wikipedia, the original text of the `needtrans` template needs to be restored.

Do I have access to push a branch based off of master and submit a pull request? If so, I can make the change myself? I won't be able to test it, though, since I'm not going to set up an entire development area on my laptop for this one change. Does someone test things like this as part of the PR approval process?

**Comment by HalHaynes** [comment]
Well, I did push a new branch, but it isn't showing up here anyway!

**Comment by NovemLinguae** [comment]
When you create and push a branch on a cloned repo, the main pages of both your cloned repo and the parent repo should have a yellow banner that says "Compare and pull request". Try clicking that to create a PR for this repo.

https://i.ytimg.com/vi/rgbCcBNZcdQ/maxresdefault.jpg

**Comment by HalHaynes** [comment]
It shows that when it finds a branch that you've pushed. It isn't finding my branch. (I don't know what you mean by "the main page of [my] cloned repo": My cloned repo is on my local computer and I'm looking at it in Visual Studio Code. It has no "main page".)

What I'm seeing in GitHub:

![image](https://user-images.githubusercontent.com/47984485/222979865-5e2e01de-2553-4010-9984-1383deb05972.png)

**Comment by NovemLinguae** [comment]
> the main page of [my] cloned repo

By that I mean https://github.com/HailHynes/twinkle. Looks like you haven't forked this repo yet. OK, I see the problem.

So the normal workflow is something like...

- Visit https://github.com/wikimedia-gadgets/twinkle
- Click the "fork" button in the top right. That'll create https://github.com/HailHynes/twinkle
- Now `git clone https://github.com/HailHynes/twinkle.git` and do all your branches, patches, changes, etc. to that.
- `git push` your branch
- Then it'll appear as in my screenshot in the post above, and you'll be able to create a PR in https://github.com/wikimedia-gadgets/twinkle
- Once the PR is submitted, you'll be in good shape. If there's any issues after that, you and I can have an additional conversation in the PR itself.

Hope this helps.

**Comment by HalHaynes** [comment]
Oh! I looked at [CONTRIBUTING.md](https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md), which says nothing about needing to create a fork. It just says to clone, edit, and push, so that's what I did.

**Comment by HalHaynes** [comment]
Ok, done! Thanks, @NovemLinguae.
